name: test
on:
- pull_request
jobs:
  fluent-mysql-driver-8_0:
    container: 
      image: swift:5.2-bionic
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: vapor_database
          MYSQL_USER: vapor_username
          MYSQL_PASSWORD: vapor_password
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --sanitize=thread
      env:
        MYSQL_HOSTNAME: mysql
  fluent-mysql-driver-5_7:
    container: 
      image: swift:5.2-bionic
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: vapor_database
          MYSQL_USER: vapor_username
          MYSQL_PASSWORD: vapor_password
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --sanitize=thread
      env:
        MYSQL_HOSTNAME: mysql
